name: Call Generate Terraform Docs

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  CallMasterTerraformWorkflow:
    uses: nimisha-gj/terraform-workflows/.github/workflows/terraform.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
